### ISSUE TITLE
多行文本溢出「…」到 autofixer 背锅再到放弃

### ISSUE THREAD

**Issue by NoName4Me** [NoName4Me/yo-CSS#3]
#### 单行

```css
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

#### 多行

* `-webkit-`

```css
overflow: hidden;
display: -webkit-box;
-webkit-box-orient: vertical;
-webkit-line-clamp: 2;
```

仅适用于 webkit 内核浏览器和移动端。**然后这里遇到了一个坑，点击[这里查看](#fuck)**。

* 强制添加 `...`

比如在伪类中增加
```scss
.gradient {
  position: relative;
  line-height: 20px;
  max-height: 40px;
  overflow:hidden;
  &::after {
    content: '...';
    position: absolute;
    bottom: 0;
    right: 0;
    padding-left: 40px;
    padding-right: 10px;
    background: linear-gradient(to right, transparent, white 55%);
  }
}
```

这个需要当文本不足（没有溢出）时，取消伪类样式。

示例：https://codepen.io/blurnull/pen/YLbrPY

【补充】纯CSS，无需 JS 判断文本未溢出情况。

> **关键点 `after` 伪类中没有设置 `bottom: 0`**

```scss
/* mixin for multiline */
@mixin multiLineEllipsis($lineHeight: 1.2em, $lineCount: 1, $bgColor: white){
  overflow: hidden;
  position: relative;
  line-height: $lineHeight;
  max-height: $lineHeight * $lineCount; 
  &:before {
    content: '...';
    position: absolute;
    right: 0;
    bottom: 0;
    padding-left: 2em;
    background: linear-gradient(to right, transparent, white 55%);
  }
  &:after {
    content: '';
    position: absolute;
    right: 0;
    width: 1em;
    height: 1em;
    margin-top: 0.2em;
    background: $bgColor;
  }
}

.higher-gradient {
  @include multiLineEllipsis($lineHeight: 1.2em, $lineCount: 2, $bgColor: white);  
}
```

参考：http://hackingui.com/front-end/a-pure-css-solution-for-multiline-text-truncation/

* JS 方案

Clamp.js：https://github.com/josephschmitt/Clamp.js

```js
$clamp(theElement, {clamp: 3});
```

<a href="" id="fuck"></a>
## 我们再来说这个坑

**坑**：在使用 `vue-cli`（结合官方提供的 webpack 模板开发）打包后，发现这个属性 `-webkit-box-orient: vertical` 总是被删除。在文件内设置忽略规则 `/* autoprefixer: ignore next */` 也没用。

`package.json` 里这个位置增加任意flex 2009浏览器即可。比如`"Safari 6"`。详见[这里](https://github.com/postcss/autoprefixer/issues/776)。

> 但是不知道这样是否会引入别的坑。如果可以，`-webkit-box-orient: vertical` 直接写到页面的 inline 属性里吧。— —||

分析一下原因吧。

1. 为什么 `-webkit-box-orient` 会被删除。因为package.json里的browserlist里包含的浏览器不认识 `-webkit-box-orient`（大概是太陈旧，已经被弃用了？）。

2. `autoprefixer` 规则 `/* autoprefixer: ignore next */` 为什么不生效。因为生产环境中，webpack 有配置了这么个插件：
  ```js
  // webpack.prod.conf.js
  new OptimizeCSSPlugin({
      cssProcessorOptions: config.build.productionSourceMap
        ? { safe: true, map: { inline: false } }
        : { safe: true }
    }),
  ```
  这个东西会启用 `autoprefixer`，即进行了**「两次」** fix（还有一次是 loader 里的 `postCSS`）。`cssProcessorOptions` 的配置改为 `{ safe: true, map: { inline: false }, autoprefixer: false }` 即可。

3. 惊不惊喜，意不意外！！！
